### ISSUE TITLE
Widget position dropdown colors

### ISSUE THREAD

**Issue by lekoaf** [g-delmo/currently-playing#4]
There seems to be some styling error with the Widget position dropdown.

Linux Debian, Chrome 86

![widget_position](https://user-images.githubusercontent.com/7765599/124913319-47389380-dfef-11eb-8f5a-df92552704c4.png)

**Comment by g-delmo** [comment]
I'll look into it, thanks for reporting

**Comment by g-delmo** [comment]
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

Does this unstyled select look good for you? I think the issue might be that since we're setting the `color: white` property on the `select` it is putting white on the white default background in your browser.

**Comment by lekoaf** [comment]
Yupp, the select in the link works fine.

**Comment by g-delmo** [comment]
Let me know if this works: https://currently-playing-git-fork-eggsy-master-g-delmo.vercel.app

**Comment by lekoaf** [comment]
Yupp, works good. Slightly too black and white, but it works at least. :smile:
